import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cn } from "@/lib/utils"
import { SiteHeader } from '@/components/common/site-header';
import { ThemeProvider } from "@/components/common/theme-provider"
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="lite">
      <body className={inter.className}>  <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      ><SiteHeader />{children}</ThemeProvider></body>
    </html>
  );
}
